CREATE TABLE users(
    usersId INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    usersNome VARCHAR(128) NOT NULL,
    usersEmail VARCHAR(128) NOT NULL,
    usersUsuario VARCHAR(128) NOT NULL,
    usersSenha VARCHAR(128) NOT NULL
)

